
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]

    modId="kataklysm"
    version="1.0"
    displayName="Kataklysm"
    logoFile="kataklysm.png"
    authors="Sakurafuld"
    description='''This mod adds something useful for Mekanism and other mods.'''

[[dependencies.kataklysm]]

    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kataklysm]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kataklysm]]

    modId="mekanism"
    mandatory=false
    versionRange="[1.18.2-10.2.5.465,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.kataklysm]]

    modId="mekanismtools"
    mandatory=false
    versionRange="[1.18.2-10.2.5.465,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.kataklysm]]

modId="mekanismgenerators"
mandatory=false
versionRange="[1.18.2-10.2.5.465,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kataklysm]]

modId="mekanismadditions"
mandatory=false
versionRange="[1.18.2-10.2.5.465,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kataklysm]]

modId="solarpanels"
mandatory=false
versionRange="[1.18.2-1.5.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.kataklysm]]

modId="botania"
mandatory=false
versionRange="[1.18.2-435,)"
ordering="AFTER"
side="BOTH"